jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:  # <<< Aqui passamos os secrets
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: ðŸ“¥ Clonar repositÃ³rio
        uses: actions/checkout@v4

      - name: ðŸ Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: ðŸ“¦ Instalar dependÃªncias
        run: pip install -r requirements.txt

      - name: â–¶ï¸ Rodar bot
        run: python bot.py
